// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrlYs4Ykzay4G3vUTbSjZhqRx4OofIUso',
    appId: '1:1006422929286:web:bdb7e180f9446b97c9c607',
    messagingSenderId: '1006422929286',
    projectId: 'noyaly-12a37',
    authDomain: 'noyaly-12a37.firebaseapp.com',
    storageBucket: 'noyaly-12a37.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTfcHpMMZuj6LCH9pDuE7Ldbd7bJtaKZk',
    appId: '1:1006422929286:android:2b5cf8885b00dcf4c9c607',
    messagingSenderId: '1006422929286',
    projectId: 'noyaly-12a37',
    storageBucket: 'noyaly-12a37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM0qmtPx-yllRf55jemoIizG75_gr363Q',
    appId: '1:1006422929286:ios:5dc4a4ff88e90a86c9c607',
    messagingSenderId: '1006422929286',
    projectId: 'noyaly-12a37',
    storageBucket: 'noyaly-12a37.firebasestorage.app',
    iosBundleId: 'com.example.noyaly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM0qmtPx-yllRf55jemoIizG75_gr363Q',
    appId: '1:1006422929286:ios:5dc4a4ff88e90a86c9c607',
    messagingSenderId: '1006422929286',
    projectId: 'noyaly-12a37',
    storageBucket: 'noyaly-12a37.firebasestorage.app',
    iosBundleId: 'com.example.noyaly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrlYs4Ykzay4G3vUTbSjZhqRx4OofIUso',
    appId: '1:1006422929286:web:b4a6df760a80cd72c9c607',
    messagingSenderId: '1006422929286',
    projectId: 'noyaly-12a37',
    authDomain: 'noyaly-12a37.firebaseapp.com',
    storageBucket: 'noyaly-12a37.firebasestorage.app',
  );
}
